### ISSUE TITLE
Dockerhub

### ISSUE THREAD

**Issue by c0rrre** [MrBrax/TwitchAutomator#6] opened 2020-10-26 10:14 UTC
Hi,

first of all nice project.
Is it possible to get it on dockerhub? 
Im currently using Unraid and the best way to get the latest docker is via dockerhub.

Thanks.

c0rrre

**Comment by MrBrax** [comment] 2020-10-26 10:36
I'm gonna have to look into that, never published any docker images before.

**Comment by MrBrax** [comment] 2020-10-26 12:16
After finally figuring out some extremely confusing documentation, i think i managed to upload it.

https://hub.docker.com/repository/docker/mrbrax/twitchautomator

I don't know if it works.

**Comment by c0rrre** [comment] 2020-10-26 12:30
Thanks for creating it on dockerhub, i found some documentation for automatic building to dockerhub.
https://docs.docker.com/docker-hub/builds/

**Comment by MrBrax** [comment] 2020-10-26 12:35
Yeah it looks neat, but it wanted full read/write access to all my repos here.

**Comment by c0rrre** [comment] 2020-10-26 12:36
alright :)
ill test the dockerhub image soon

**Comment by danyal** [comment] 2020-12-04 08:39
Would love a docker image as well. @c0rrre did you test this?

**Comment by MrBrax** [comment] 2020-12-04 08:40
anyone's free to build docker images, it's not in my priorities until php 7.4 is added to the image i use, unless someone does a pull request

**Comment by danyal** [comment] 2020-12-04 08:41
Makes sense, thanks for the fast reply!

**Comment by KurtzPT** [comment] 2020-12-21 00:31
> anyone's free to build docker images, it's not in my priorities until php 7.4 is added to the image i use, unless someone does a pull request

The following image uses php 7,4: `erseco/alpine-php7-webserver:edge`, can you update it?

**Comment by MrBrax** [comment] 2020-12-21 10:02
> 
> 
> > anyone's free to build docker images, it's not in my priorities until php 7.4 is added to the image i use, unless someone does a pull request
> 
> The following image uses php 7.4: `erseco/alpine-php7-webserver:edge`, can you update it?

if it uses the exact same config and paths maybe

**Comment by KurtzPT** [comment] 2020-12-21 11:54
> > > anyone's free to build docker images, it's not in my priorities until php 7.4 is added to the image i use, unless someone does a pull request
> > 
> > 
> > The following image uses php 7.4: `erseco/alpine-php7-webserver:edge`, can you update it?
> 
> if it uses the exact same config and paths maybe

It's a fork from the image you are using at the moment, so it should be similar.

**Comment by MrBrax** [comment] 2020-12-21 12:40
That version outputs `PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 2200606 bytes) in Unknown on line 0` when trying to run composer. I guess that's why it's the edge version.

**Comment by MrBrax** [comment] 2020-12-21 12:55
alright, managed to get around it and pushed a new image out

**Comment by KurtzPT** [comment] 2020-12-21 15:05
It seems to be working, until I had a crash by changing one setting. I don't think it's related to the docker itself so I created a new issue here #13

**Comment by MrBrax** [comment] 2020-12-21 19:50
you should get a subscription response too

**Comment by KurtzPT** [comment] 2020-12-21 19:59
> you should get a subscription response too

Does the **app url** need to be the external server IP and be accessible outside (internet)? I think that might be the problem, but I'm not sure since I can't see anything about it on readme.

**Comment by MrBrax** [comment] 2020-12-21 20:01
> 
> 
> > you should get a subscription response too
> 
> Does the **app url** need to be the external server IP and be accessible outside (internet)? I think that might be the problem, but I'm not sure since I can't see anything about it on readme.

yes, as that is the url twitch servers need to contact.

it's mentioned in requirements as "Public facing webserver (nginx, apache, etc)"

**Comment by KurtzPT** [comment] 2020-12-21 21:05
> > Does the **app url** need to be the external server IP and be accessible outside (internet)? I think that might be the problem, but I'm not sure since I can't see anything about it on readme.
> 
> yes, as that is the url twitch servers need to contact.
> 
> it's mentioned in requirements as "Public facing webserver (nginx, apache, etc)"

Alright thanks for the quick answers, I managed to get the subscription response. I'm still having troubles with the https/insecure password but I'll try and debug it myself.

**Comment by KurtzPT** [comment] 2020-12-22 09:28
Couple of questions I have:

1)
TwitchAutomator is always saying `streamlink exited but capturing didn't complete` while recording, is this normal?
![image](https://user-images.githubusercontent.com/14930057/102871898-e83a7500-4436-11eb-8f25-3eea368f2e58.png)

2)
The download chat option only works after the stream has ended and when the VOD is available, I guess because it didn't work for me. Unfortunately most streamers I know have VODs disabled because of the DMCA stuff going on so I have to test out the "chat_dump" option which you refer as unstable. 

My suggestion here is maybe rename the "download chat" to include somehow VOD/After Stream, so it's not misleading like it was for me for the first time, thinking it was going to download chat on the fly while the stream is playing.

Otherwise it seems it is working, which is great!
![image](https://user-images.githubusercontent.com/14930057/102872746-0c4a8600-4438-11eb-8d32-cba39d6435cc.png)

**Comment by MrBrax** [comment] 2020-12-22 11:17
yeah that shouldn't happen at all, must be a docker issue, which i can't really solve since i don't have a setup

the live chat capture isn't really recommended since executed processes from php stop while it's not outputting anything, making the capture pause for great amounts of time

**Comment by KurtzPT** [comment] 2020-12-22 11:48
> yeah that shouldn't happen at all, must be a docker issue, which i can't really solve since i don't have a setup. some log output would be helpful though

I think I know why this is happening, I'm seeing in the logs that the command ps -p is not recognized, which I verified by running the same command inside the running image:

![image](https://user-images.githubusercontent.com/14930057/102885543-6ef94d00-444b-11eb-91a4-170b38d5ab6c.png)

Let me know if you want to try running other commands to test it out.

> the live chat capture isn't really recommended since executed processes from php stop while it's not outputting anything, making the capture pause for great amounts of time

That's unfortunately, that way streamers that don't save vods/vods disabled will not have any chat at all.

**Comment by MrBrax** [comment] 2020-12-22 12:01
should be fixed in the docker image i'm pushing now

**Comment by KurtzPT** [comment] 2020-12-22 12:20
> should be fixed in the docker image i'm pushing now

Confirmed it is working now:

![image](https://user-images.githubusercontent.com/14930057/102888129-0fea0700-4450-11eb-9009-755f843bde81.png)

**Comment by KurtzPT** [comment] 2020-12-22 12:51
This is a bit off topic but since I can't see any other way of contacting you, I'm going to put this here:

Have you checked this website: https://twitcharchives.com/deleted-vods ? It seems with this we could get deleted vods and maybe download chat with it.

![image](https://user-images.githubusercontent.com/14930057/102890382-4164d180-4454-11eb-92dc-d0cb2b7ee3de.png)

For example last moonmoon stream that I recorded is there in the first row, TwitchAutomator couldn't find the vod because it was deleted/not saved.

**Comment by MrBrax** [comment] 2020-12-22 13:07
yes, there are hidden api endpoints for that, i haven't really delved into it though

**Closed** 2020-12-22 15:04 UTC

**Comment by MrBrax** [comment] 2021-11-17 15:55
> That's unfortunately, that way streamers that don't save vods/have vods disabled will not have any chat saved at all.

dev branch now includes a brand new chat dumper which seems to be way more stable than the old one, a 10 hour stream seems to get dumped fine
i'll bump this up to main when i've used it more

**Comment by KurtzPT** [comment] 2021-11-17 18:04
I found an error on the dev branch, the APK package is not `node` but `nodejs`.

**Comment by MrBrax** [comment] 2021-11-17 18:53
> 
> 
> I found an error on the dev branch, the APK package on Dockerfile is not `node` but `nodejs`.

ah, i was wondering about that, just took a guess, thanks
